### ISSUE TITLE
InfoRSS toolbar spring left in status bar even if location is set to top

### ISSUE THREAD

**Issue by FranklinDM** [ThosRTanner/inforss#144]
I have set the location of the infoRSS toolbar to be on top/bottom, but it still leaves a big space in the status bar. I inspected and found that even if I change the location, the toolbar spring is still left in the status bar.

Here's my suggestion: 
`Insert this at line 1577`
``` js
document.getElementById("inforss.toolbar.spring").setAttribute("collapsed", "false");
```

`Insert this at line 1595`
``` js
document.getElementById("inforss.toolbar.spring").setAttribute("collapsed", "true");
```

**Comment by ThosRTanner** [comment]
Will fiddle around with that. I've actually not seen palemoon withoout inforss in it for ages, so I no longer remember what a plain toolbar looks like.
