### ISSUE TITLE
Displaying feed with non-Unicode content is wrong

### ISSUE THREAD

**Issue by silv7k** [ThosRTanner/inforss#147]
![2017-10-13_20-59-29](https://user-images.githubusercontent.com/32778144/31559490-7aa888b6-b059-11e7-867f-4061fda1cac1.png)
I have a couple of feeds that still stick to non-Unicode encoding (Cyrillic windows-1251 in my case), and while there's trend to migrate to Unicode, this is an issue for me now.
Note: old infoRSS extension displayed these feeds correct!
Feed with problems: http://lleo.me/dnevnik/rss.xml

**Comment by ThosRTanner** [comment]
As the ultimate in hacks while I investigate a proper fix for this, try adding `encoding="WINDOWS-1251"` to the entry for the feed inforss.xml, so you get something like this:

    <RSS url="http://lleo.me/dnevnik/rss.xml" title="Леонид Каганов: блог" selected="false" nbItem="9999" lengthItem="25" playPodcast="false" savePodcastLocation="" purgeHistory="120" browserHistory="true" filterCaseSensitive="true" link="http://lleo.me/dnevnik/" description="Леонид Каганов: блог" icon="http://lleo.me/favicon.ico" refresh="15" activity="true" filter="all" type="rss" groupAssociated="false" group="false" encoding="WINDOWS-1251"/

(depending on your other settings obviously).

This is an unfortunate side effect of a massive cleanup in the way fetches were handled and that it appears you need to know the encoding of an xml file before you fetch it.

**Comment by ThosRTanner** [comment]
Note to self: Need to see if I can work out the encoding on adding the feed

**Comment by silv7k** [comment]
I’ve closed Pale Moon, added the option you suggested, started Pale Moon.
Got these errors at start:
![2017-10-14_19-46-23](https://user-images.githubusercontent.com/32778144/31577518-bdaeddd0-b118-11e7-8bda-c1cca56691dc.png)
![2017-10-14_19-46-52](https://user-images.githubusercontent.com/32778144/31577520-c269b200-b118-11e7-8c2d-6b59ee572397.png)
Then browser started OK, but no feeds in infoRSS.
No infoRSS-related errors in web console.

**Comment by silv7k** [comment]
I can live with your hack as a workaround, don’t really need a fix for this.
