### ISSUE TITLE
Feed ixbt.com is not shown 

### ISSUE THREAD

**Issue by silv7k** [ThosRTanner/inforss#148]
http://www.ixbt.com/export/utf8/articles.rss
I see no obvious reason for this, but the feed is simply not displayed.
Old infoRSS extension had no problem with the feed, but this may be a temporary issue. Like some content may just block the whole feed (because of parsing error maybe?).

**Comment by ThosRTanner** [comment]
Oddly I can't open this page in edge either. it doesn't recognise it as RSS.

**Comment by silv7k** [comment]
No problem in Advanced/Report:
![2017-10-14_19-27-19](https://user-images.githubusercontent.com/32778144/31577377-e767ee94-b115-11e7-8e94-15d4d3ff83ad.png)
In Error console I don’t see any problems with this particular feed (after swithing to it and manual refresh). The latest logged problems are:
```
14.10.2017 19:26:25
Warning: Unknown pseudo-class or pseudo-element 'listcell'.  Ruleset ignored due to bad selector.
Source file: chrome://inforss/skin/inforssTree.css
Line: 46, Column: 4
Source code:
xul:listcell > xul:image
 ----------
14.10.2017 19:26:26
Warning: Expected end of value but found '93'.  Error in parsing value for 'font-family'.  Declaration dropped.
Source file: chrome://inforss/content/inforssOption.xul
Line: 0, Column: 8
Source code:
Bauhaus 93
 ----------
14.10.2017 19:26:26
Warning: Expected end of value but found '.'.  Error in parsing value for 'font-family'.  Declaration dropped.
Source file: chrome://inforss/content/inforssOption.xul
Line: 0, Column: 9
Source code:
Modern No. 20
 ----------
14.10.2017 19:32:17
Warning: Expected end of value but found '93'.  Error in parsing value for 'font-family'.  Declaration dropped.
Source file: chrome://inforss/content/inforssOption.xul
Line: 0, Column: 8
Source code:
Bauhaus 93
 ----------
14.10.2017 19:32:17
Warning: Expected end of value but found '.'.  Error in parsing value for 'font-family'.  Declaration dropped.
Source file: chrome://inforss/content/inforssOption.xul
Line: 0, Column: 9
Source code:
Modern No. 20
```

**Comment by ThosRTanner** [comment]
I don't know if it's related but I've never seen those error messages about font-family before.

**Comment by silv7k** [comment]
> I don't know if it's related but I've never seen those error messages about font-family before.

I honestly have no idea where does this come from. I don’t have files with ’Bauhaus 93’, ’Modern No. 20’ or even ’font-family’ text strings in my Pale Moon profile directory.
These errors are caught every time I open infoRSS options (right-click on feed icon in status bar).

> It says it has 40 headlines, none unread and none new. Is 'show viewed headlines' enabled? If it isn't and you enable it, do they come back?

Yes, they do come back!! What does that mean? The newest entries in the feed are from today, I’ve definitely not marked them as read in any way. I’ve restarted browser a number of times today, checked the feed a number of times manually.
(Only I don’t have ’show viewed headlines’ option, I’ve disabled ’hide viewed headlines’ option.)

The name of the feed is OK, just renamed it.

**Comment by ThosRTanner** [comment]
That means it thinks you've read the headlines already. Either by clicking them or viewing them some other way so they're in the browser history already.

Not offhand sure why that would have happened though. 

Also, sorry, I tend to lose track of the options as there are so many.

**Comment by silv7k** [comment]
Ha! Yes, you are right, I’d read the articles linked in the headlines before they got to the feed.
So not a bug after all, just my personal stuff.

Did you made this change to the extension? Cause old infoRSS did displayed the entries with links I’ve already visited.

**Comment by ThosRTanner** [comment]
Yes. There's an option in the general tab that says 'use local history to hide read headlines' that was completely broken (and had been for a long time I think). I fixed it. I imagine that you have that switched on. (I certainly hope that's the case!)

**Comment by silv7k** [comment]
Yes, I have this option switched on (probably switched a long time ago since it did nothing).
Now I've switched it off, will test it today.

**Comment by silv7k** [comment]
After switching the option off and restarting browser the feed is displayed OK.
Closing the issue.
