### ISSUE TITLE
After switching to a new feed the whole feed area in status bar is a bit misplaced

### ISSUE THREAD

**Issue by silv7k** [ThosRTanner/inforss#149]
![2017-10-13_21-21-16](https://user-images.githubusercontent.com/32778144/31560309-75ff5e36-b05c-11e7-8755-29bc35d6ff17.png)
That's what happening every time I switch to a new feed or start a browser.
My workaround is to customize toolbar (just open the configuration window and close it, no real changes), then the problem is fixed automatically.
![2017-10-13_21-28-16](https://user-images.githubusercontent.com/32778144/31560564-730f352e-b05d-11e7-89e1-e2053372e0b2.png)
Really a minor bug.
I’m on Windows 7 with 125% system-wide interface zoom settings.

**Comment by ThosRTanner** [comment]
I can't see what the difference is between those 2?
