### ISSUE TITLE
Exception caught when clicking on feed icon (as to select a new feed) after updating prefs until browser restart

### ISSUE THREAD

**Issue by silv7k** [ThosRTanner/inforss#152]
![2017-10-16_00-39-26](https://user-images.githubusercontent.com/32778144/31589562-877bebbe-b20c-11e7-853e-0a3e9ee52863.png)
There’s also a new error message in console every time:
`16.10.2017 0:52:14
Warning: ReferenceError: deprecated caller usage
Source file: chrome://inforss/content/modules/inforssDebug.jsm
Line: 145`
Never had this problem till today.
This has happened the first time I started browser with option ’Use local history to hide read headlines’ switched to off. I’ve tried switch it on and off and restart browser, but can’t reproduce the problem.

**Comment by silv7k** [comment]
It happened every time until I’d restarted browser. Never happened since then.

**Comment by ThosRTanner** [comment]
There is something there that I should look at. I've noticed intermittent problems when updating the preferences - something appears not to get reset quite right.

**Comment by ThosRTanner** [comment]
Am going to close this, because there has been a serious amount of refactoring since this was raised, and the way the popups are populated has been reworked considerably
