### ISSUE TITLE
Getting a completely blank options screen on linux

### ISSUE THREAD

**Issue by souxd** [ThosRTanner/inforss#344]
NixOS (Linux x86_64)
DE: SwayWM 1.8.1 (Wayland)
Palemoon 32.2.0 64-Bit (AVX build)
InfoRSS 2.3.1.0
other statusbar extensions: Pendactyl
statusbar also has the icons of Ublock Origin and Ematrix for convenience

All together seems to only get the feed from the default RSS, but not of the recently added ones. I assume this is because it's a group but i can't tell because the option menu options doesn't seem to have any effect except click the top tabs and click the buttons "cancel" and "okay".
![swappy-20230527_110750](https://github.com/ThosRTanner/inforss/assets/51197853/a391bb9a-e438-47a0-a914-26d39b2bed4a)

**Comment by ThosRTanner** [comment]
Thank you for reporting this. If you have a blank options window like that it generally means there's been some sort of error when bringing up the options window. Can you check the browser console?

I note you're running on linux, which sadly isn't really an option I have and there might be differences with the way things run on linux.

**Comment by ThosRTanner** [comment]
What is dactyl? the nearest thing i can find is pentadactyl and that says not compatible with version 32.2

**Comment by ThosRTanner** [comment]
I have tried to reproduce this and I can't. inforss + ublock + dactyl + ematrix work fine for me, and the option screen comes up as expected.

What other extensions do you have? And have you tried disabling them until you get a setup that works? I've certainly come across extensions that have very little to do with the status bar which do nasty things and stop inforss working

**Comment by ThosRTanner** [comment]
In passing, all together is just a group. It doesn't automatically get feeds added to it, you have to do that manually.

**Comment by ThosRTanner** [comment]
Can you check inforss.debug.log in about:config is set to true. If not, set it and try showing the option window again and see if you get anything logged.

Also can you check what is in the other tabs (advanced, credits, help). this is looking very odd.

**Comment by ThosRTanner** [comment]
Ah. thank you. that explains why the option window is failing to initialise. Now to work out why that happens on linux but not windows >.<

**Comment by ThosRTanner** [comment]
Can you try using this patched version to see if it fixes your issue?

[inforss.zip](https://github.com/ThosRTanner/inforss/files/11593106/inforss.zip)

**Comment by ThosRTanner** [comment]
saying?

**Comment by ThosRTanner** [comment]
thanks

**Comment by ThosRTanner** [comment]
OK, can you try this?
[inforss.zip](https://github.com/ThosRTanner/inforss/files/11593315/inforss.zip)

**Comment by ThosRTanner** [comment]
urgh

**Comment by ThosRTanner** [comment]
Attempt the 3rd...

[inforss.zip](https://github.com/ThosRTanner/inforss/files/11593407/inforss.zip)

**Comment by ThosRTanner** [comment]
OK, got wsl and palemoon installed i really need to persuade it to match the windows scaling, it hurts my eyes! Anyway, fixed a couple of other issues and now this allows you to use the options window on linux

[inforss.zip](https://github.com/ThosRTanner/inforss/files/11593889/inforss.zip)
