### ISSUE TITLE
Pale Moon Forum Issue - Proxy Request

### ISSUE THREAD

**Issue by jabcreations** [ThosRTanner/inforss#367]
Hi, I apologize in advance as this isn't for the RSS feed though I wanted to try to make Moon Child aware that the forums seem to be broken. I can't sign in or register. I tried new VPN address with a completely wiped browser so I don't believe it's a ban issue (I have no reason to believe I was banned). Might be a chance that after the somewhat recent falling out Moon Child missed a database password or something. I have no idea how to contact him and thosrtanner's user name appears here and as a recent thread starter. My user name on there is jabcreations (or JAB Creations).

**Comment by ThosRTanner** [comment]
there's a comment on the forums saying someone had to use a different browser to register.

**Comment by jabcreations** [comment]
The registration is broken regardless of using Pale Moon, Waterfox, Firefox or Vivaldi, all in private mode or cleared storage/cache/cookies/etc. I explicitly attempted to register a second account using Pale Moon itself. The forums are broken and if he's only spending his time on there then he's isolated from people trying to make him aware of what is going on.
